# pre-commit install
# pre-commit run --all-files
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_commit_msg: "chore(deps): update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  autoupdate_schedule: "weekly"
  skip:
    - uv-lock
    - pip-compile
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  # * Top level
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        exclude: ^uv[.]lock|.*\.ipynb
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
        exclude: SRS_data$|SWF_Adsorption_data$
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  # * meta hooks
  - repo: meta
    hooks:
      - id: check-hooks-apply
        stages: [manual]
      - id: check-useless-excludes
        stages: [manual]

  # * pyproject.toml
  # ** format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.16.2
    hooks:
      - id: pyproject-fmt
        args: [--indent=4, --keep-full-version]
        files: ""
        types: [toml]
  # ** validate
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
  # ** validate (schema-store)
  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: 2026.02.22
    hooks:
      - id: validate-pyproject
        name: validate-pyproject-schema-store
        stages: [manual]
  # ** repo review
  - repo: https://github.com/scientific-python/cookie
    rev: 2026.03.02
    hooks:
      - id: sp-repo-review
        stages: [manual]

  # * Prettier
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier
        alias: markdownlint
        stages: [pre-commit, manual]

  # * Markdown
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.21.0
    hooks:
      - id: markdownlint-cli2
        alias: markdownlint
        args: [--style, prettier]
        # language_version: 10.9.0

  # * Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        alias: ruff
        types_or: &ruff-types-or [python, pyi, jupyter]
        args: [--fix, --show-fixes]
      - id: ruff-format
        alias: ruff
        types_or: *ruff-types-or
  # To be replace by ruff analog when I find one ...
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==25.9.0

  # * Spelling
  # ** typos
  # Revert to crate-ci/typos if https://github.com/crate-ci/typos/issues/390 is fixed.
  # - repo: https://github.com/crate-ci/typos
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.44.0
    hooks:
      - id: typos
        exclude_types: [jupyter]
        exclude: ^uv[.]lock$|^requirements
  # ** codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: [-I, docs/spelling_wordlist.txt]
        exclude_types: [jupyter]
        exclude: ^uv[.]lock$|^requirements
        stages: [manual]

  # * Dependencies
  # ** pyproject2conda
  - repo: https://github.com/usnistgov/pyproject2conda
    rev: v0.22.1
    hooks:
      - id: pyproject2conda-project
        alias: requirements
  # ** uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.7
    hooks:
      - id: uv-lock
        alias: requirements
        args: [--locked]
      - id: pip-compile
        alias: requirements
        entry: python tools/requirements_lock.py
        pass_filenames: true
        files: ^requirements/[^/]*\.txt$

  # * Commit message
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # * Justfile
  - repo: local
    hooks:
      - id: just-fmt
        name: just-fmt
        entry:
          bash -c 'for x in "$@"; do just --fmt --unstable --justfile "$x";
          done' --
        language: system
        files: \.?[jJ]ustfile|.*\.just$
        stages: [manual]

  # * Cruft
  - repo: https://github.com/cruft/cruft.git
    rev: 2.16.0
    hooks:
      - id: cruft
        args: [--checkout, main]
        stages: [manual]

  # * Notebook specific --------------------------------------------------------
  # * Strip out metadata from notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
        args:
          [
            --keep-output,
            --keep-count,
            --extra-keys,
            "metadata.kernelspec metadata.kernel_spec",
          ]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      # ** typos
      - id: nbqa
        name: nbqa-typos
        alias: typos
        additional_dependencies: &typos-deps [typos==1.38.1] # make sure save version as above.
        args: [typos, --nbqa-shell]
        # this can lead to errors, so use with care
        # args: [typos, --write-changes, --nbqa-shell]
      - id: nbqa
        name: nbqa-typos-markdown
        alias: typos
        additional_dependencies: *typos-deps
        args: [typos, --nbqa-shell, --nbqa-md]
        # this can lead to errors, so use with care
        # args: [typos, --write-changes, --nbqa-shell, --nbqa-md]

      # ** codespell
      - id: nbqa
        name: nbqa-codespell
        alias: codespell
        additional_dependencies: &codespell-deps [codespell==2.4.1, tomli] # make sure same as above
        args:
          [codespell, --ignore-words=docs/spelling_wordlist.txt, --nbqa-shell]
        stages: [manual]
      - id: nbqa
        name: nbqa-codespell-markdown
        alias: codespell
        additional_dependencies: *codespell-deps
        args:
          [
            codespell,
            --ignore-words=docs/spelling_wordlist.txt,
            --nbqa-shell,
            --nbqa-md,
          ]
        stages: [manual]

  # ** symlink in notebooks from example/usage to docs/example/usage
  - repo: local
    hooks:
      - id: symlink-docs-examples-notebooks
        name: symlink-docs-examples-notebooks
        entry: python tools/symlink_docs_examples_notebooks.py
        language: python
        files: ^docs/examples/.*\.md$
        pass_filenames: false
