name: thermoextrap-env
channels:
  - conda-forge
  - wpk-nist
dependencies:
  - python=3.8
  - setuptools
  - sympy
  - matplotlib
  - numpy
  - scipy
  - xarray
#  - openmm
  - cmomy
  - pymbar=3.1.0
  # - pip
  # - pip:
  #     - tensorflow
  #     - tensorflow-probability
  #     - gpflow
# prefix: /Users/wpk/miniforge3/envs/gpflow_test
