name: thermoextrap-dev
channels:
  - conda-forge
  - wpk-nist
dependencies:
  - python=3.8
  - sympy
  - matplotlib
  - numpy
  - scipy
  - xarray
  - openmm
  - cmomy
  - pymbar
  - pip
  - pip:
      - tensorflow
      - tensorflow-probability
      - gpflow
# prefix: /Users/wpk/miniforge3/envs/gpflow_test
