[build-system]
build-backend = "uv_build"
requires = [
    "uv-build>=0.12.1,<0.13.0",
]

[project]
name = "thermoextrap"
version = "1.2.1"
description = "Thermodynamic extrapolation"
readme = "README.md"
keywords = [
    "thermoextrap",
]
license = "NIST-PD"
license-files = [ "LICENSE" ]
authors = [
    { name = "Jacob Monroe", email = "jacob.monroe@nist.gov" },
    { name = "William Krekelberg", email = "wpk@nist.gov" },
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "attrs>=24.1.0",
    "cmomy>=1.0.3",
    "dm-tree",
    "lazy-loader",
    "module-utilities[inherit]>=0.11.0",
    "numba>=0.60.0",
    "numpy>=1.26.0",
    "packaging",
    "scipy",
    "sympy",
    "xarray>=2024.7.0",
]

[project.optional-dependencies]
accel = [
    "bottleneck",
]
all = [
    "thermoextrap[accel,gpr,mbar,parallel,viz]",
]
gpr = [
    "gpflow>=2.9.0",
    # gpflow bug.  Needs this, but doesn't include by default
    "setuptools<81.0.0",
    "tensorflow>=2.16,<2.17; python_version<'3.13' and (sys_platform=='darwin' and platform_machine=='x86_64')",
    "tensorflow>=2.16; python_version<'3.13' and (sys_platform!='darwin' or platform_machine!='x86_64')",
    "tensorflow>=2.20; python_version>='3.13' and sys_platform=='linux'",
    "tensorflow-probability[tf]~=0.24.0",
]
mbar = [
    "pymbar[jax]>=4.0",
]
openmm = [
    "openmm",
]
parallel = [
    "dask[complete]",
]
viz = [
    "matplotlib",
]

[project.urls]
Documentation = "https://pages.nist.gov/thermoextrap/"
Homepage = "https://github.com/usnistgov/thermoextrap"

[dependency-groups]
dev = [
    "nbconvert",
    "righttyper",
    "thermoextrap[all]",
    { include-group = "mypy" },
    { include-group = "notebook" },
    { include-group = "nox" },
    # { include-group = "pytest-accept" },
    { include-group = "test" },
    { include-group = "test-notebook" },
    { include-group = "type" },
]
test = [
    "pytest-cov",
    "pytest-env",
    "pytest-sugar",
    "pytest-xdist>3.6.0",
    "thermoextrap[gpr,mbar]",
    { include-group = "pandas" },
    { include-group = "pytest" },
]
type = [
    "matplotlib; python_version=='3.12'",
    "pandas-stubs",
    "scipy-stubs; python_version>='3.10'",
    "thermoextrap[gpr,mbar]",
    "types-tensorflow",
    { include-group = "nox" },
    { include-group = "pylint" },
    { include-group = "pytest" },
    { include-group = "typecheck-runner" },
]
docs = [
    "autodocsumm",
    "myst-nb",
    "pyenchant",
    "sphinx>=5.3.0",
    # other
    "sphinx-book-theme",
    "sphinx-copybutton",
    "sphinxcontrib-spelling",
    "thermoextrap[gpr,mbar,viz]",
]
# other groups
basedpyright = [ "basedpyright>=1.39.9" ]
docs-live = [
    "sphinx-autobuild",
    { include-group = "docs" },
]
docs-spelling = [
    "pyenchant",
    "sphinxcontrib-spelling",
    { include-group = "docs" },
]
ipython = [ "ipython" ]
mypy = [ "mypy[faster-cache]>=2.3.0" ]
notebook = [ "ipykernel", "nbclient" ]
nox = [ "dotenv", "nox>=2026.7.11" ]
pandas = [ "pandas>=2.3" ]
pylint = [ "pylint" ]
pytest = [ "pytest" ]
pytest-accept = [ "pytest-accept" ]
test-extras = [
    { include-group = "test" },
]
test-notebook = [
    "coverage<=7.13.0",
    "nbval",
    "thermoextrap[viz]",
    { include-group = "test" },
]
typecheck-runner = [ "typecheck-runner>=0.2.0; python_version>'3.9'" ]

# * uv -------------------------------------------------------------------------
[tool.uv]
required-version = ">=0.11.8"
default-groups = [ "dev" ]
fork-strategy = "requires-python"
environments = [
    "python_version<'3.13' and (sys_platform!='darwin' or platform_machine!='x86_64')",
    "python_version<'3.13' and (sys_platform=='darwin' and platform_machine=='x86_64')",
    "python_version>='3.13' and sys_platform=='linux'",
    # "python_version<'3.13' and (sys_platform=='darwin' and platform_machine=='x86_64')",
    # "python_version<'3.13' and (sys_platform!='darwin' or platform_machine!='x86_64')",
]
exclude-newer = "7 days"
managed = true
build-backend.source-exclude = [ ".*cache" ]
build-backend.source-include = [ "tests/**" ]
pip.annotation-style = "line"
pip.generate-hashes = true

[tool.uv.dependency-groups]
dev.requires-python = ">=3.12"
docs.requires-python = ">=3.12"
docs-live.requires-python = ">=3.12"
docs-spelling.requires-python = ">=3.12"
ipython.requires-python = ">=3.12"
mypy.requires-python = ">=3.12"
notebook.requires-python = ">=3.12"
nox.requires-python = ">=3.12"

# ruff -------------------------------------------------------------------------
[tool.ruff]
extend-include = [
    "*.ipynb",
]
extend-exclude = [
    ".numba_cache",
    ".venv",
    "dist-conda",
    "examples/gpr_active_learning",
    "tests/legacy/",
]
fix = true
# unsafe-fixes = true

[tool.ruff.format]
docstring-code-format = true
preview = true  # needed for markdown support

[tool.ruff.lint]
preview = true
select = [
    "ALL",
]
# fixable = [ "ALL" ]
unfixable = [
    "PLR6104",
    "ERA",
    "T",
]
ignore = [
    "ANN401",  # - Any ok sometimes
    "COM",     # - flake8-commas, formatter should take care of this?
    "CPY",     # - Don't require copyright
    "D105",    # - Missing magic method docstring
    "D107",    # - Missing docstring in __init__
    "D203",    # - 1 blank line required before class docstring
    "D205",    # - blank line after summary
    "D212",    # - Multi-line docstring summary should start at the first line
    "D400",    # - First line should end with a period
    "D401",    # - First line of docstring should be in imperative mood: "{first_line}"
    "DOC201",  # - Missing return from documentation
    "DOC501",  # - Missing raises from documentation
    "E501",    # - line too long - let formatter fix this
    "E731",    # - do not assign a lambda expression, use a def
    "FBT",     # - bools are ok
    "PLC0415", # - import should be at top level (leads to issues with imports in func?)
    "S404",    # - Want to use subprocess sometimes
    "S603",    # - subprocess-without-shell-equals-true
    "S607",    # - start-process-with-partial-path
    "TID252",  # - Allow relative imports
    # numpy/pandas
    "NPY",     # - not using numpy?
    "PD",      # - not using pandas?
]
isort.known-first-party = [
    "thermoextrap",
]
pydocstyle.convention = "numpy"
pylint.max-args = 15
pylint.max-positional-args = 15
pylint.max-public-methods = 30
ruff.strictly-empty-init-modules = false

# Project specific ignores
[tool.ruff.lint.per-file-ignores]
"src/**/*.py" = [
    "ARG002",
    "D102",    # - Missing docstring in public method
    "DOC202",
    "DOC402",
    "ERA",     # - eradicate (want to keep some stuff)
    "FIX002",
    "N801",
    "N802",
    "N803",
    "N815",
    "PD",      # - not using pandas?
    "PLR2004", # - numbers in comparison sometimes ok
    "TD003",
    "UP031",
]
"src/**/gpr_active/*.py" = [
    "N806",
    "PLR0914",
    "PLR6301",
]
"tests/**/*.py" = [
    "D",       # - Don't need to document tests
    "S101",    # - Assert is fine with tests
    "ANN",
    "E402",
    "ERA",
    "NPY",
    "PD",
    "PLR0914",
    "PLR2004",
    "PT011",
    "SLF001",
]
"examples/usage/**/*.ipynb" = [
    "ANN",
    "B018",    # - Don't remove useless expressions in notebooks
    "ARG001",
    "ARG002",
    "D",
    "E302",
    "E305",
    "ERA",
    "N801",
    "N802",
    "N803",
    "N806",
    "N816",
    "PLR2004",
    "PLR6104",
    "PTH111",
    "PTH207",
    "T201",
]
"examples/usage/gpr/**/*.ipynb" = [
    "B008",
    "FA100",
    "PERF203",
    "PERF401",
    "PLR0911",
    "PLR6301",
]

# * Checks ---------------------------------------------------------------------
[tool.repo-review]
ignore = [
    "NOX103", # I prefer using "nox.options.sessions"
    "PC111",  # use doccmd instead of blacken-docs
    "PC140",  # do this externally
    "PC160",  # use typos
    "PC170",  # pygrep
]

[tool.check-wheel-contents]
src_dir = [ "src" ]
toplevel = [ "thermoextrap" ]

[tool.pyproject-fmt]
indent = 4
keep_full_version = true
max_supported_python = "3.13"
expand_tables = [
    "project.entry-points",
    "project.optional-dependencies",
    "project.scripts",
    "project.urls",
    "tool.mypy.overrides",
    "tool.pyproject2conda",
    "tool.pyright.executionEnvironments",
    "tool.pytest",
    "tool.ruff.format",
    "tool.ruff.lint",
    "tool.ruff.lint.per-file-ignores",
    "tool.typos",
    "tool.uv.dependency-groups",
    "tool.uv.exclude-newer-package",
]

[tool.typos.default]
extend-ignore-identifiers-re = [
    ".*equil.*",
    "NDArray.*",
    "struc_.*",
]
# nbqa generated
extend-ignore-re = [ "# %%NBQA-.*" ]

[tool.typos.default.extend-identifiers]
CPY = "CPY"
gather_nd = "gather_nd"
numer = "numer"
pertNumer = "pertNumer"

[tool.typos.files]
extend-exclude = [ "spelling_wordlist.txt" ]

[tool.typos.type.jupyter]
# only check file name for notebooks.  Use nbaq for contents.
check-file = false

# * typecheck ---------------------------------------------------------------------
[tool.mypy]
files = [
    "noxfile.py",
    "src",
    "tests",
    "tools",
]
# options
check_untyped_defs = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
enable_error_code = [
    "ignore-without-code",
    "redundant-expr",
    "truthy-bool",
]
strict = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "matplotlib.*",
    "numba.*",
    "pymbar.*",
    "scipy.*",
    "sympy.*",
    "tensorflow_probability.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "tests.*",
]
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
strict = false

[[tool.mypy.overrides]]
module = [ "tests.legacy.*" ]
check_untyped_defs = false

[tool.pyrefly]
enabled-ignores = [ "pyrefly" ]
project-includes = [
    "examples/usage/*.ipynb",
    "noxfile.py",
    "src",
    "tests",
    "tools",
]
search-path = [ "." ]

[tool.pyright]
typeCheckingMode = "standard"
strict = [
    "noxfile.py",
    "src/thermoextrap/*.py",
    "src/thermoextrap/core/*.py",
    "src/thermoextrap/gpr_active/ig_active.py",
    # "src/thermoextrap/gpr_active/active_utils.py",
    # "src/thermoextrap/gpr_active/gp_models.py",
    "src/thermoextrap/gpr_active/sine_active.py",
    "tests/test_typing.py",
    "tools/*.py",
]
include = [
    # TODO(wpk): enable this
    # "examples/usage/*.ipynb",
    "noxfile.py",
    "src",
    "tests",
    "tools",
]
exclude = [
    "**/.mypy_cache",
    "**/.numba_cache",
    "**/__pycache__",
    "**/legacy/*.py",
    ".nox/**",
    ".tox/**",
    ".venv/**",
]
enableTypeIgnoreComments = false
deprecateTypingAliases = true
reportCallInDefaultInitializer = true
reportImplicitOverride = true
reportImplicitStringConcatenation = false
reportImportCycles = true
# reportMissingSuperCall = true
reportOverlappingOverload = true
reportPrivateImportUsage = false
reportPrivateUsage = false
reportPropertyTypeMismatch = true
reportUninitializedInstanceVariable = true
reportUnnecessaryTypeIgnoreComment = true
reportUnreachable = "warning"
reportUntypedClassDecorator = true
reportUntypedFunctionDecorator = true
reportUnusedCallResult = true
reportUnusedImport = false
reportUnusedVariable = false
enableReachabilityAnalysis = false

[[tool.pyright.executionEnvironments]]
reportArgumentType = false
reportCallIssue = false
reportImplicitOverride = false
reportUnusedCallResult = false
root = "tests"

[[tool.pyright.executionEnvironments]]
reportUnusedCallResult = false
root = "examples/usage"

[tool.ty]
src.include = [
    "examples/usage/*.ipynb",
    "noxfile.py",
    "src",
    "tests",
    "tools",
]
analysis.respect-type-ignore-comments = false

# * Testing --------------------------------------------------------------------
[tool.pytest.ini_options]
addopts = [
    "--cov-config=pyproject.toml",
    "--doctest-glob=*.md",
    "--doctest-modules",
    "--ignore-glob='**/legacy/**",
    "--pyargs",
    "--pytest-env-verbose",
    "--strict-config",
    "--strict-markers",
    "-ra",
    # xdist
    "-n",
    "4",
]
testpaths = [
    "README.md",
    "tests",
    "thermoextrap",
]
# options
filterwarnings = [
    "error",
    "ignore: A kernel object:UserWarning",
    "ignore: FNV hashing is not implemented in Numba:UserWarning",
    "ignore: Module thermoextrap was never imported:coverage.exceptions.CoverageWarning",
    "ignore: No data was collected:coverage.exceptions.CoverageWarning",
    "ignore: The default datetime:DeprecationWarning",
    "ignore: Type google:DeprecationWarning",
    "ignore: Unknown solver options",
    "ignore: distutils Version classes are deprecated:DeprecationWarning",
    "ignore: importing 'Const' from 'astroid' is deprecated:DeprecationWarning",
    "ignore: invalid escape sequence:DeprecationWarning",
    "ignore: invalid escape sequence:SyntaxWarning",
    "ignore: pkg_resources is deprecated as an API:DeprecationWarning",
    "ignore: pkg_resources is deprecated:UserWarning",
]
log_cli_level = "INFO"
log_level = "INFO"
minversion = "8"
strict_xfail = "true"

[tool.pytest_env]
CMOMY_NUMBA_PARALLEL = { value = "false", skip_if_set = true }
NUMBA_CACHE_DIR = { value = "{PWD}/.numba_cache", transform = true, skip_if_set = true }
NUMBA_CACHE_LOCATOR_CLASSES = { value = "tools.numba_cache_tools.SharedHashCacheLocator", skip_if_set = true }
NUMBA_CACHE_TOOLS_MAGIC = { value = "0", skip_if_set = true }
env_files = [ ".numba_env" ]

[tool.coverage]
run.branch = true
run.source = [
    "thermoextrap",
]
paths.source = [
    "src",
    # needed for testing source if not editable install
    ".nox/**/site-packages",
    "*/.nox/**/site-packages",
    "*/src",
]
report.exclude_also = [
    "@overload",
    "if TYPE_CHECKING:",
]
report.include = [
    "src/*",
]
report.omit = [
    "*/_typing.py",
    "*/vendored/*",
]
report.show_missing = true

[tool.commitizen]
use_shortcuts = true

# * Dependency creation --------------------------------------------------------
[tool.pyproject2conda]
template-python = "requirements/py{py}-{env}"
template = "requirements/{env}"
name = "py{py}-{env}"
python = "default"
channels = "conda-forge"
style = "yaml"
conda-deps = "pip"

[tool.pyproject2conda.dependencies]
pytest-accept = { pip = true }
matplotlib = { skip = true, packages = "matplotlib-base" }
lazy-loader = { skip = true, packages = "lazy_loader" }
dask = { skip = true, packages = "dask" }
gpflow = { pip = true }
tensorflow = { pip = true }
tensorflow-probability = { pip = true }
pymbar = { pip = true }
jax = { pip = true }
module-utilities = { packages = "docstring-inheritance" }

[tool.pyproject2conda.envs.dev]
groups = "dev"

[tool.pyproject2conda.envs.test]
groups = [ "test" ]
python = "all"

[tool.pyproject2conda.envs.test-extras]
groups = [ "test-extras" ]
python = "all"
skip-package = true

[tool.pyproject2conda.envs.uvx-tools]
pip-deps = [
    # these used solely for specking tools to be run via uvx ...
    "conda-lock>=4.0.2",
    "copier-template-extensions>=0.3.3",
    "copier>=9.17.0",
    "grayskull>=3.1.1",
    "nbqa>=1.9.1",
    "prek>=0.4.12",
    "pyrefly>=1.2.0",
    "pyright>=1.1.411",
    "rooster>=0.1.1",
    "twine>=7.0.0",
    "ty>=0.0.65",
]
groups = [
    "basedpyright",
    "mypy",
    "nox",
    "typecheck-runner",
]
skip-package = true
style = "requirements"

[tool.uv-locker]
pip-compile-config-file = "requirements/uv.toml"
scripts = [
    "noxfile.py",
    "tools/check_dist_version.py",
    "tools/clean_kernelspec.py",
]

[[tool.uv-locker.requirements]]
path = "requirements/uvx-tools.txt"
output-file = "requirements/lock/uvx-tools.txt"
python = "min"
options = [
    "--no-deps",
    "--no-strip-extras",
    "--universal",
]

# * Other tools ----------------------------------------------------------------
[tool.rooster]
changelog_contributors = true
major-labels = [ "breaking" ]
minor_labels = [ "enhancement" ]
patch-labels = [ "bug", "documentation" ]
# options
ignore-labels = [ "internal" ]
require-labels = [ "breaking", "bug", "documentation", "enhancement" ]
version_files = [
    "pyproject.toml",
]
# sections
section-labels."Breaking changes" = [ "breaking" ]
section-labels."Bug fixes" = [ "bug" ]
section-labels.Documentation = [ "documentation" ]
section-labels.Enhancements = [ "enhancement" ]
section-labels.Internal = [ "internal" ]
section-labels."Other changes" = [ "__unknown__" ]
