# need this to pick up requires-python from pyproject.toml
extend = "./pyproject.toml"
extend-include = [
    "*.ipynb",
]
extend-exclude = [
    ".numba_cache",
    ".venv",
    "dist-conda",
    # "tests/",
    # "src/testpackage_book_nocli/tests",
    "examples/gpr_active_learning",
    "src/thermoextrap/legacy/",
]
fix = true
# unsafe-fixes = true

[format]
docstring-code-format = true

[lint]
preview = true
select = [
    "ALL",
]
# fixable = ["ALL"]
unfixable = [
    "ERA",
    "PLR6104",
    "T",
]
ignore = [
    "ANN401",  # - Any ok sometimes
    "COM",     # - flake8-commas, formatter should take care of this?
    "CPY",     # - Don't require copyright
    "D105",    # - Missing magic method docstring
    "D107",    # - Missing docstring in __init__
    "D203",    # - 1 blank line required before class docstring
    "D205",    # - blank line after summary
    "D212",    # - Multi-line docstring summary should start at the first line
    "D400",    # - First line should end with a period
    "D401",    # - First line of docstring should be in imperative mood: "{first_line}"
    "DOC201",  # - Missing return from documentation
    "DOC501",  # - Missing raises from documentation
    "E501",    # - line too long - let formatter fix this
    "E731",    # - do not assign a lambda expression, use a def
    "FBT",     # - bools are ok
    "S404",    # - Want to use subprocess sometimes
    "S603",    # - subprocess-without-shell-equals-true
    "S607",    # - start-process-with-partial-path
    "PLC0415", # - import should be at top level (leads to issues with imports in func?)
    "TID252",  # - Allow relative imports
]
# Use extend-ignore for project specific ignores. Prefer lint.extend-per-file-ignores."src/**/*.py" below
# extend-ignore = [ ]
isort.known-first-party = [
    "thermoextrap",
]
pydocstyle.convention = "numpy"
pylint.max-args = 15
pylint.max-positional-args = 15
pylint.max-public-methods = 30

[lint.per-file-ignores]
"docs/conf.py" = [
    "ERA",    # - Some helpful commented out code in conf.py
    "INP001", # - Namespace package fine for docs
]
"noxfile.py" = [
    "RUF009", # - Allow `add_option` for DataClassParser
]
"tests/**/*.py" = [
    "D",    # - Don't need to document tests
    "S101", # - Assert is fine with tests
]

# Project specific ignores (avoid changing per-file-ignores directly)
# extend-per-file-ignores."path/to/file.py" = [ ... ]
[lint.extend-per-file-ignores]
"**/*.ipynb" = [
    "ANN",
    "B018", # - Don't remove useless expressions in notebooks
    # "D100",  # - undocumented-public-module
    # "INP001",
    "ERA",
    "E302",
    "E305",
    "ARG001",
    "ARG002",
    "D",
    "N801",
    "N802",
    "N803",
    "N806",
    "N816",
    "PLR6104",
    "PLR2004",
    "PTH111",
    "PTH207",
    "T201",
]
"src/**/*.py" = [
    "ANN", # - Annotations (just use mypy/pyright)
    # "D102",    # - Missing docstring in public method
    # "D103",    # - Missing docstring in public function
    # "D202",    # - blank line after docstring
    # "D415",    # - First line should end with a period, question mark, or exclamation point
    # "D417",    # - Missing argument description in the docstring for {definition}: {name} (bad with docfiller)
    # "DOC202",  # - Missing return from documentation
    # "E402",    # - module level import not at top of file
    "ERA", # - eradicate (want to keep some stuff)
    # "ISC",     # - flake8-implicit-str-concat
    "NPY", # - not using numpy?
    # "SLF001",  # - flake8-self (private access sometimes OK)
    "PD",      # - not using pandas?
    "PLR2004", # - numbers in comparison sometimes ok
    # "PLR0913", # - complexity sometimes ok
    # "PLR0917", # - complexity sometimes ok
    "DOC202",
    "DOC402",
    "UP031",
    "FIX002",
    "TD003",
]
"tests/**/*.py" = [
    "ANN",
    "ERA",
    "E402",
    "PLR2004",
    "NPY",
    "PD",
    "PLR0914",
    "PT011",
    "SLF001",
]
"**/_attrs_utils.py" = [ "A002", "ARG001" ]
"**/adaptive_interp.py" = [ "T201" ]
"**/beta.py" = [ "A003", "ARG002", "D102", "N801" ]
"**/data*.py" = [
    "D102",
]
"**/gpr_active/*.py" = [
    "ARG002",
    "D102",
    "D103",
    "FA100",
    "ISC",
    "N802",
    "N803",
    "N806",
    "PLR0914",
    "PLR6301",
]
"**/lnpi.py" = [
    "A003",
    "ARG002",
    "D102",
    "N801",
    "N802",
    "N815",
]
"**/models.py" = [
    "A003",
    "ARG002",
    "D102",
    "N803",
    "N815",
]
"**/stack.py" = [
    "D102",
]
"**/thermoextrap/random.py" = [ "A005" ]
"**/typing.py" = [ "A005" ]
"**/volume*.py" = [
    "D102",
]
"conftest.py" = [
    "ANN",
    "D103",
]
"examples/usage/gpr/**/*.ipynb" = [
    "B008",
    "FA100",
    "PERF203",
    "PERF401",
    "PLR0911",
    "PLR6301",
]
# Project specific ignores (avoid changing per-file-ignores directly)
"tests/test_lnPi.py" = [
    "N999",
]
