name: "PR checks"

on: # zizmor: ignore[dangerous-triggers]
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions: {}

jobs:
  validate-title:
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label-from-title:
    name: Auto-label PR
    permissions:
      contents: read
      pull-requests: write
      statuses: write
      checks: write
    runs-on: ubuntu-slim
    steps:
      - uses: fuxingloh/multi-labeler@b15a54460c38f54043fa75f7b08a0e2aa5b94b5b # v4.0.0

  validate-branch-name:
    name: Validate branch name
    runs-on: ubuntu-slim
    steps:
      - if: github.head_ref == 'main' || github.head_ref == 'master'
        run: |
          echo "Error: Pull requests from branch $GITHUB_HEAD_REF not allowed"
          exit 1
        shell: bash
